### ISSUE TITLE
merge data command

### ISSUE THREAD

**Issue by pranathivemuri** [mehta-lab/microDL#119]
Documenting discussion with @smguo Basically one might have training data across different folders from different datasets. microdl must have a way to copy and merge all the 3 frames_meta.csv files for the 3 datasets and form one folder with one dataset for training and one csv file.

**Comment by smguo** [comment]
Thanks @pranathivemuri for opening the issue! I've implemented a simple script where the users can specify in the config what datasets to merge, the script will then copy the datasets to the new location and merge the individual frames_meta.csv (or generate it if it doesn't exist). It will come in my next PR. Let me know if you have any suggestion for the implementation

**Comment by ziw-liu** [comment]
Implemented as https://github.com/czbiohub-sf/iohub/pull/154
