### ISSUE TITLE
memory mapping the tiles used for training

### ISSUE THREAD

**Issue by pranathivemuri** [mehta-lab/microDL#120]
we have redundant copies of training data after tiling. @smguo suggested we should make use of numpy memmap - https://github.com/czbiohub/bam2fasta/blob/master/bam2fasta/np_utils.py#L5 to write these tiles.

**Comment by smguo** [comment]
The idea is creating a numpy memmap object for the entire dataset, during each mini-batch, the dataset   generator will randomly sample tile indices and slice it from the numpy memmap object (tiling during training). This will avoid creating large copies of tiles and allows sampling tiles in a non-grid like pattern

**Comment by smguo** [comment]
This feature can also be implemented using Dask or Zarr

**Comment by jennyfolkesson** [comment]
Perhaps add zarr support first (https://github.com/czbiohub/microDL/issues/140) then implement this feature in zarr after that?

**Comment by ziw-liu** [comment]
The pytorch implementation now operates on OME-Zarr with iohub. (https://github.com/mehta-lab/microDL/pull/209)
