### ISSUE TITLE
Add support for Zarr as input format

### ISSUE THREAD

**Issue by smguo** [mehta-lab/microDL#140]
microDL currently only accepts single-paged tiff as input format but microscopy community is switching to zarr format. Add support for zarr format will reduce data conversion and duplication.

**Comment by smguo** [comment]
@jennyfolkesson here is a hcs-zarr dataset on ESS:
`/gpfs/CompMicro/projects/HEK/2021_09_16_HEKs_8orgs_OC43_63x_04NA/first_TL.zarr`

You can use [waveorder](https://github.com/mehta-lab/waveorder/blob/master/waveorder/io/reader.py) read each position as a numpy array, e.g.:

`from waveorder.io.reader import WaveorderReader`
`reader = WaveorderReader(input_path, data_type='zarr')`
`img_tcz = reader.get_zarr(position=pos_idx)`

where `img_tcz` is a numpy array with dimension (t, c, z)

**Comment by jennyfolkesson** [comment]
Closing this issue as it is taken care of with https://github.com/mehta-lab/microDL/pull/172.
