### ISSUE TITLE
Add test dataset

### ISSUE THREAD

**Issue by JohannaRahm** [mehta-lab/microDL#144]
How about adding or referencing a test dataset with which the pipeline can be tried out. This would allow external users to clearly see which data structure is required and make the adaption to their dataset & setup easier.

**Comment by mattersoflight** [comment]
The useful test dataset is large (several GB). It is now shared via google drive and downloadable with this [shell script ](https://github.com/mehta-lab/microDL/blob/master/notebooks/dlmbl2022/download_data.sh).
