### ISSUE TITLE
z-alignment of different modalities

### ISSUE THREAD

**Issue by JohannaRahm** [mehta-lab/microDL#160]
Hi together,

I wanted to prepare training data that cover different modalities, so we can compare the impact of phase vs brightfield and deconvolved vs not deconvolved channels. However, I get an unexpected behavior of the z-alignment script. The script simply copies all single page tif file images into the new aligned folder, without aligning them (from the 97 z-ids per position all z-ids are saved in the aligned folder).

I plan to preparing following training data combinations:
1. Phase & non deconvolved fluorescence channels
2. Brightfield & deconvolved fluorescence channels
3. Brightfield & non deconvolved fluorescence channels
4. Phase & deconvolved fluorescence channels --> these are the modalities the current model is trained on, z-alignment works

The scripts are located here:
`/gpfs/CompMicro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_single_page/`
1. `align_z_focus_2022_03_15_only_phase_refmem_min25_max60.py`
2. `align_z_focus_2022_03_15_only_deconv_refmem_min25_max60.py`
3. `align_z_focus_2022_03_15_raw_data_refmem_min25_max60.py`
4. `align_z_focus_2022_03_15_refmem_min25_max60.py`. -> this script works! Aligned images are saved at `/gpfs/CompMicro/projects/HEK/2022_03_15_orgs_nuc_mem_63x_04NA/all_pos_single_page/all_pos_Phase1e-3_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50_registered_refmem_min25_max60`

Furthermore, the alignment script takes quite a while to run through. If anyone finds time it would be great to speed the script up with e.g. multiprocessing.

I ran the scripts on hulk in a microDL docker container with the command `python <script name>`

I would highly appreciate if anyone finds time to debug this issue! Please let me know if there are open questions / if I can help with anything.

Best,
Johanna

**Comment by mattersoflight** [comment]
Closing, because z-alignment is now part of the reconstruction and registration pipelines outside of microDL.
