### ISSUE TITLE
Split of microDL pipeline usage on HPC and power9 machines

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#163]
I have been using microDL by splitting the workflow across HPC cluster and the docker environment on power i9 machine. I have been predominantly using microDL to perform virtual staining using phase images. The initial data preparation and preprocessing is performed on HPC, and training and inference steps on the docker on power i9.

The first form of data which is the primary input to the pipeline is the stack of brightfield images captured on the microscopes. The  first step is the phase image reconstruction from the brightfield image stacks using waveorder library, after which they are aligned to get the focal plane centered at every imaged position. The reconstructed phase images are input to the microDL preprocessing step. The following workflow is well implemented by occasional visual checks of resulting images by the user, which is easier using napari and imageJ (best used on HPC).

The next steps of training and inference are performed in the docker environment on power i9 machine. The following steps cannot be implemented elsewhere currently due to unstable environment on HPC and lower disk space availability on machines like fry2 (very slow training speed).  So, it is currently best implemented in the docker environment.

**Comment by ziw-liu** [comment]
Power9 nodes are being retired. Can we close this now?
