### ISSUE TITLE
Modifying inference to apply trained model on data with different channel order

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#170]
How can I modify the inference configuration to use a trained model on a dataset which has different order of channel than the dataset which was used for training? 
For instance, consider two datasets A and B. The datasets have captured in the following order:
Dataset A : nucleus =channel 0, membrane =channel 1, phase =channel 2.
Dataset B: phase =channel 0, mitochondria =channel 1.
If I trained a microDL model on dataset A to predict the nucleus using phase images, how can I modify the inference configuration to work on dataset B to virtually stain the nucleus from the phase channels?

**Comment by Christianfoley** [comment]
You should be able to just modify the '**input_channels**' and '**target_channels**' parameters under the 'dataset' parameter in the `inference_config.yml` file. In your case, I believe setting them to [0] and [1] respectively should do the trick.

**Comment by Soorya19Pradeep** [comment]
Thank you for the help @Christianfoley! Let me summarize the exchange we had here and feedback from @jennyfolkesson.

Virtual staining inference on datasets with one label-free and one fluorescence channels works well, but using the model for inference on datasets with just phase channel gave blank images. The pixel value of the predicted images were zeros.

The images were normalized by the target channel (phase channel here), which yielded subzero pixel values. Based on suggestion from @jennyfolkesson, the predicted images were compressed to uint16 format before saving, which converted the subzero values to zeros.

To test this we saved the uncompressed predicted image as numpy array modifying few lines of code in: 
microDL/micro_dl/inference/image_inference.py

The changes I used based on the @Christianfoley 's suggestion have been marked with '#edit: save uncompressed copy'

`        if self.model_task == 'regression':
            uncompressed_im_pred = im_pred             #edit: save uncompressed copy
            im_pred = np.clip(im_pred, 0, 65535)
            im_pred = im_pred.astype(np.uint16)
        else:
            # assuming segmentation output is probability maps
            uncompressed_im_pred = im_pred              #edit: save uncompressed copy
            im_pred = im_pred.astype(np.float32)
        # Check file format
	
        if self.image_ext in ['.png', '.tif']:
            if self.image_ext == '.png':
                assert im_pred.dtype == np.uint16, \
                    'PNG format does not support float type. ' \
                    'Change file extension as ".tif" or ".npy" instead'
            cv2.imwrite(file_name, np.squeeze(im_pred))
        elif self.image_ext == '.npy':
            # TODO: add support for saving prediction of 3D slices
            np.save(file_name + '_uncompressed', np.squeeze(uncompressed_im_pred), allow_pickle = True)
            np.save(file_name, np.squeeze(im_pred), allow_pickle=True)
        else:
            raise ValueError(
                'Unsupported file extension: {}'.format(self.image_ext),
            )`

The change saved images with the expected prediction. The pixel values were still much less than zero (-0.0023 to 0.126). The images saved can be rescaled back to 0 to 255 range for standardization.
