### ISSUE TITLE
Flatfielding computation error on gunpowder dataloading branch

### ISSUE THREAD

**Issue by Christianfoley** [mehta-lab/microDL#198]
With certain parameters flatfielding a dataset seems to exacerbate the aberations it is trying to correct. @Soorya19Pradeep If you get a chance please comment what configs and datasets you used to produce this issue.

**Comment by Soorya19Pradeep** [comment]
@Christianfoley, this is the path to the config file used for preprocessing:
`/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/config_files/torch_gpLoading_2023_01/torch_config_nucl25D.yml`

This is the path to the input in zarr format with added mask channel and flatfield used for correction:
`/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_VeroA549_2022_12_14/Inputs_nucl/A549_20X.zarr`

**Comment by Soorya19Pradeep** [comment]
This was caused by the segmentation of wrong channel. In my case the segmentation was performed on the label-free channel. This was solved by specifying the right channel for segmentation in preprocessing section of config file.
