### ISSUE TITLE
configs should use channel names and not channel index

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/microDL#201]
**Channel names in config**
The data loader should allow users to specify inputs and outputs by channel names. Let's not use channel index, because they are an easy source of confusion. As the data is preprocessed, the channel indices can shift. `iohub` is now public and has features to add new channels. It will soon have features to [delete and rewrite channels.](https://github.com/czbiohub/iohub/issues/45)

Discovered during #197

**Comment by mattersoflight** [comment]
@Christianfoley , @Soorya19Pradeep 
iohub now provides methods to index, rename, and update channels by name, e.g., [get_channel_index].(https://github.com/czbiohub/iohub/blob/f32f7f015c9121db512c94741f7966a640f87e01/iohub/ngff.py#L255)

**Comment by ziw-liu** [comment]
Implemented in #209 and #220.
