### ISSUE TITLE
z-score

### ISSUE THREAD

**Issue by yingmuzhi** [mehta-lab/microDL#204]
Hi,there.In the script normalize.py, zscore, use median and interquartile range to replace mean and standard deviation.why? what is the difference between using median or mean. It is very nice of you to help me out this Question, thanks:)

**Comment by Christianfoley** [comment]
Hi @yingmuzhi. We have noticed that for some of our data, using median and IQR over mean and STD helps to preserve information about the dynamic range of our samples and generate the most accurate intensity prediction (see section _Data preprocessing for model training_ in "[Revealing architectural order with quantitative label-free imaging and deep learning](https://elifesciences.org/articles/55502)"). 

While this has worked for our data in the past, the normalization scheme is by all means a hyperparameter, and can be tuned to the distribution that best fits your data.
