### ISSUE TITLE
Inference shouldn't use gunpowder

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#206]
@mattersoflight and I had a discussion on the structure of the inference module. The inference module currently uses gunpowder and we dont want that in the inference. @mattersoflight did bring up a valid point that if we want to use the model elsewhere we want to keep the inference implementation simple, avoiding installation of gunpowder. 

The input zarr dataset can be read in using iohub and the predictions can be generated. Then as a separate module evaluation metrics can be implemented. @Christianfoley, can we implement the inference without using gunpowder?

**Comment by Christianfoley** [comment]
>... can we implement the inference without using gunpowder?

Hi @Soorya19Pradeep. It can certainly be done but it would take some work to rewrite the underlying dataset. The reason I used gunpowder to feed inference is that:

1. It's fast, so we can move a large amount of data quickly without having to reimplement multiprocessing (which we have had issues with in the past)
2. The dataset object used to feed the training could be reused to feed inference, with some modifications.

I will note that it has become somewhat more complicated because of the changes to the HCS spec that @ziw-liu informed me of recently while were discussion the integration of IOHub, but these complications also apply to training and preprocessing.

I'm not sure I understand how removing gunpowder from the inference module allows users to avoid installing gunpowder. Do we anticipate different pypy releases for "microDL with training" and "microDL inference only" (related #189)?

**Comment by ziw-liu** [comment]
> Do we anticipate different pypy releases for "microDL with training" and "microDL inference only" (related #189)?

Training dependencies can be under a extra tag, just like `[dev]` dependencies.

**Comment by Soorya19Pradeep** [comment]
Hello @Christianfoley. Thank you for the explaining the reasons for the current implementation! We will be implementing the trained model in pipelines for online virtual staining (in the future) and will be putting it out for other applications. The inference must be simple enough, doesn't require to perform the predictions at a fast rate. The simplicity of the inference is more important than speed at this point. 

Basically, we want to pick image of one FOV each time, (a small stack of z slice if 2.5D model), normalize it and feed to the model and generate the prediction. Some of the datasets i need to run inference on has exactly 30 images of just phase, just one channel with no z stack or time points. We have information on the FOVs corresponding to the set to be used for generating inference from data split yaml file, and the user provides other specific information related to the z stack and window size through the config.

I don't know if we need the window size. I would anticipate the user would feed the whole image and get the predicted image of the same size. This is what I would expect. What do you think @mattersoflight ?

**Comment by Soorya19Pradeep** [comment]
Update on the inference module:
- We will use [iohub](https://github.com/czbiohub/iohub) to load zarr files for performing inference. @Christianfoley is working on this and extending the use of iohub for other modules on `iohub_dependency` branch. The layout of plan by @mattersoflight :
> * Support the full feature set (including adding/deleting/renaming channels) only with ome-zarr v 0.4 format.
> * Convert all the datasets to this version of ome-zarr. The imread utility in iohub can read the old ome-zarr format.
> * Ziwen will actively contribute code to the inference module to make this happen.
- The use of iohub requires zarr stores to be in >0.3 HCS-NGFF format, which is not the current format. The test data created with the new format has the following structure. ![image](https://user-images.githubusercontent.com/101817974/224860010-719b34f5-dca2-4d8f-ad11-b22980de6877.png)
- The zarr store created for testing `/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_A549_2023_02_07/Input_Nucl/A549_20X_iohubTest.zarr` and the config file is `/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/config_files/torch_gpLoading_2023_02/torch_config_nucl25D_iohubTest.yml`.

**Comment by Christianfoley** [comment]
Resolved!  [commit 15e9be1](https://github.com/mehta-lab/microDL/commit/15e9be1fbad2aa1762c9d3e4662a00b17b7a6b5b).
