### ISSUE TITLE
Convert existing tensorflow models to pytorch

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#208]
As we convert the microDL pipeline to work with pytorch we need models for the infected cell project to predict nucleus and membrane in HEK cells. It will be efficient to convert the existing HEK nucleus and membrane prediction models @JohannaRahm trained to work with pytorch rather than retraining them. We can convert these models using onnx from tensorflow to pytorch. @ziw-liu, do you have any suggestions or pointers?

**Comment by mattersoflight** [comment]
@Soorya19Pradeep @ziw-liu I suggest you try two paths:

## Convert working tensorflow models to a deployable format (@ziw-liu ):
(All of the following links are to the release 1.0.0 commit, which we have tested extensively):

As @Soorya19Pradeep pointed out, current tensorflow implementation [saves only weights and not the architecture](https://github.com/mehta-lab/microDL/blob/0420d46d32a42a960ef30d49aff99b5611b3bbb2/micro_dl/train/trainer.py#LL101C8-L101C8). But, there is a [`load_model`](https://github.com/mehta-lab/microDL/blob/0420d46d32a42a960ef30d49aff99b5611b3bbb2/micro_dl/inference/model_inference.py#L7) method in inference module,  which can create a model based on config and weights. It is used in [training method](https://github.com/mehta-lab/microDL/blob/0420d46d32a42a960ef30d49aff99b5611b3bbb2/micro_dl/cli/train_script.py#L271). 

I have not used this feature before, but @jennyfolkesson may remember if resuming the training from saved model ever worked. If it did, the `load_model` method can be adapted to export the model such that it can be deployed with pytorch.

Interestingly, this project on model management and conversion tools that may be handy: https://github.com/Microsoft/MMdnn

It will be great to reuse these models. 

@Soorya19Pradeep please note paths of 2  tensorflow models whose inferences you recently used that @ziw-liu  can work with.

b) Convert the dataset to `ome-zarr` format and use equivalent hyper parameters to train the model from scratch. @Soorya19Pradeep and @Christianfoley can drive this, and we can discuss this on separate issue.

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , you can use these model weights generated and saved by @JohannaRahm :

/hpc/projects/CompMicro/projects/virtualstaining/2022_microDL_nuc_mem/models/2022_03_15_nuc_mem/loss_functions/heavy_augmentation_z25-60_mae/Model_2022-09-14-10-18-31.hdf5

/hpc/projects/CompMicro/projects/virtualstaining/2022_microDL_nuc_mem/models/2022_03_15_nuc_mem/loss_functions/heavy_augmentation_z12-74_mae/Model_2022-05-11-13-46-08.hdf5

The model was trained to predict membrane and nucleus from phase in HEK cells.

**Comment by Soorya19Pradeep** [comment]
On discussion with @mattersoflight and @ziw-liu it was decided we will not be porting the weights from models trained on tensorflow version of microDL to pytorch or onnx. This was primarily required to compare the quality of prediction from the tensorflow model to the pytorch model. 

We will instead produce the tensorflow model predictions required for comparison on fry2.
