### ISSUE TITLE
Does inference need its own config file?

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/microDL#211]
As of https://github.com/mehta-lab/microDL/pull/210/commits/505bba8941caadccb086a015e6a094c5fee33c7f the inference CLI script requires a config file. And the pipeline will look for a `model_metadata.yml` config file in the model directory. So essentially inference requires at least 2 config files, with one being a partial duplicate of the other. Given that the parameters *required* to run inference on an already preprocessed data is relatively small, it might make sense to not provide them from a separate config file but from CLI arguments. For reproducibility, the CLI calls can be written in a shell script.

**Comment by Christianfoley** [comment]
Resolved in newer version of inference see [commit 15e9be1](https://github.com/mehta-lab/microDL/commit/15e9be1fbad2aa1762c9d3e4662a00b17b7a6b5b).
