### ISSUE TITLE
Training on gpu-c-1 scratch space

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#217]
I have been observing errors on using the microDL pytorch pipeline on dataset stored on scratch directory of gpu-c-1. 
With the earlier version of code from `gunpowder_dataloading` branch and 0.1 version of zarr preprocessed input, there was error related to reading the data during training. 

Later I tried using the 'iohub_dependency' branch and tried out the preprocessing on 0.4 NGFF zarr and was again running into issues. Log from the one of the preprocessing run is here:
`/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_HEK_2022/out_preprocessing.txt`
The preprocessing seems to run, but the output seems very different from running the preprocessing on the same dataset and config file on disk. For instance, the mask does not seem to be generated and stored and the dataset and the computation seems to run only on position 0. 

All the above computations worked perfectly well when performed on the same dataset on disk.

**Comment by ziw-liu** [comment]
There seems to be an [iohub warning](https://github.com/czbiohub/iohub/blob/9b3e3ec076eb1c16777f6a0c8198f7b2a27e9a63/iohub/ngff.py#L244-L253) in your logs:
```text
WARNING:root:Skipped item at 0: invalid <class 'type'>.
WARNING:root:Skipped item at 0: invalid <class 'type'>.
WARNING:root:Skipped item at 0: invalid <class 'type'>.
```
Have you pushed your preprocessing code to https://github.com/mehta-lab/microDL/pull/213?

**Comment by Soorya19Pradeep** [comment]
Yes. It is not present with the run from the disk. Also I am working from the clean cop of the branch `iohub_dependency` without any modifications.

**Comment by ziw-liu** [comment]
@Soorya19Pradeep are you on the HEAD of `main` for your iohub installation?

**Comment by Soorya19Pradeep** [comment]
Thank you @ziw-liu ! What is different when the data is on disk or scratch, since the code doesn't change. Does the data become untracked array on scratch?

**Comment by ziw-liu** [comment]
> Thank you @ziw-liu ! What is different when the data is on disk or scratch, since the code doesn't change. Does the data become untracked array on scratch?

It shouldn't. I suspect that some file system discrepancy covered this bug when you processed the data on an external storage server.

**Comment by ziw-liu** [comment]
Fixing in https://github.com/mehta-lab/microDL/pull/209/commits/fee41b31bc5711170ca889be3a6bc5725c455816.

**Comment by ziw-liu** [comment]
Training now works on local disk.
