### ISSUE TITLE
Normalization statistics don't need to be stored with additional key

### ISSUE THREAD

**Issue by Christianfoley** [mehta-lab/microDL#223]
Normalization statistics have been moved to their FOV or dataset attrs, and can be named under the channel name directly, without the additional "fov_statistics" or "dataset_statistics" key like in this data:
`/local/scratch/groups/cmanalysis.grp/microDL_SP/Input/HEK_2022_03_15_Phase5e-4_Denconv_Nuc8e-4_Mem8e-4_pad15_bg50_32slicesHCS.zarr/plate/0/0/`

Zattrs normalization:
<img width="727" alt="Screen Shot 2023-04-11 at 4 11 38 PM" src="https://user-images.githubusercontent.com/59987950/231308012-71aeb9f1-128e-4ed3-85e6-92d49dd65820.png">

**Comment by ziw-liu** [comment]
Fixed in #188
