### ISSUE TITLE
Runtime error testing lightning pipeline

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/microDL#227]
I am running into a runtime error disrupting the training using the current `pytorch_implementation` branch.

> RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.

Does this come from any parameter I set on config or the code itself?

**Comment by ziw-liu** [comment]
How many GPUs do you have? Currently it doesn't work with multiple GPUs.

For a Slurm session check with:

```sh
echo $CUDA_VISIBLE_DEVICES
```

If there's more than one you will need to manually modify this line to use one specific GPU:

https://github.com/mehta-lab/microDL/blob/d80516c379e81fdffac4a44a3bfb16d9380a0544/micro_dl/light/fit_example.yml#L6

**Comment by Soorya19Pradeep** [comment]
Thanks @ziw-liu! It works with one gpu. 
Is it normal for the error to appear a while after the training starts? I am trying to understand if my training is slow. I am working on the scratch space on gpu-c-1.

**Comment by ziw-liu** [comment]
> Is it normal for the error to appear a while after the training starts?

Depending on what do you mean by 'start'. By default it will first do several dummy validation iterations as a sanity check, which might omit the multi-GPU error.

Slow training should be unrelated to this though. In my experiments it seemed to be I/O bound. Can you provide more information about the hardware resources and training config?

**Comment by Soorya19Pradeep** [comment]
I have reserved an OnDemand session on gpu-c-1 with one gpu, with 32 nodes, 20GB memory per node. The training config I am using is here:
`/local/scratch/groups/cmanalysis.grp/microDL_SP/config/lit_test/HEK_dNucl_2023_04_21_15.yml`
It seems to have trained for 70 epochs over a day. 

I am also not seeing any logging from the training. The `default_root_dir` is set to this folder on the config:
`/local/scratch/groups/cmanalysis.grp/microDL_SP/logs/lit_test/`. Is there any other parameter that needs to be changed on my config to start logging? Or is it not able to log on scratch space?

**Comment by ziw-liu** [comment]
> I have reserved an OnDemand session on gpu-c-1 with one gpu, with 32 nodes, 20GB memory per node. The training config I am using is here:
> `/local/scratch/groups/cmanalysis.grp/microDL_SP/config/lit_test/HEK_dNucl_2023_04_21_15.yml`
> It seems to have trained for 70 epochs over a day.

70 epochs/day is not too bad IMO. But you can probably get better performance by using more CPU cores (e.g. 64) in data loading.
