### ISSUE TITLE
Add config parameter checks

### ISSUE THREAD

**Issue by jennyfolkesson** [mehta-lab/microDL#62]
Make sure settings are compatible with model selection, or (even better) remove settings from config file and automatically set them based on model selection.

E.g. dataset -> squeeze should be set to true for 2D models and false otherwise.

**Comment by pranathivemuri** [comment]
related to this @smguo and I discussed of potentially adding to our example config files definitions of the parameters in the comments - https://github.com/mehta-lab/reconstruct-order/blob/master/examples/example_configs/config_example.yml

**Comment by mattersoflight** [comment]
Will be available by default due to pytorch-lightning CLI/config utilities.
